[tool.poetry]
name = "environment-mlflow-client"
version = "1.0.0"
description = "environment scoped mlflow client"
authors = ["Team Sigma <team.sigma@ns.nl>"]
license = "LICENSE.txt"
readme = "README.md"
packages = [{include = "environment_mlflow_client"}]

[tool.poetry.dependencies]
python = "^3.9"
mlflow = "^2.0.1"
psutil = "^5.9.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
