name: Build and release on tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.7.1"
      - run: poetry install
      - run: poetry build --format wheel
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
