name: Build and release on tag

on:
  tags:
    - "*"

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.3.1" 
      - run: poetry install
      - run: poetry build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"