name: Linting and code coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.7.1" 
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run pylint --fail-under=9 */
      - run: poetry run pytest tests --cov environment_mlflow_client --cov-fail-under 85
